SELECT
    COUNTIF(category IS NULL) AS category_nulos,
    COUNTIF(city IS NULL) AS city_nulos,
    COUNTIF(country IS NULL) AS country_nulos,
    COUNTIF(customer_ID IS NULL) AS customer_ID_nulos,
    COUNTIF(customer_name IS NULL) AS customer_name_nulos,
    COUNTIF(discount IS NULL) AS discount_nulos,
    COUNTIF(market IS NULL) AS market_nulos,
    COUNTIF(unknown IS NULL) AS unknown_nulos,
    COUNTIF(order_date IS NULL) AS order_date_nulos,
    COUNTIF(order_id IS NULL) AS order_id_nulos,
    COUNTIF(order_priority IS NULL) AS order_priority_nulos,
    COUNTIF(product_id IS NULL) AS product_id_nulos,
    COUNTIF(product_name IS NULL) AS product_name_nulos,
    COUNTIF(profit IS NULL) AS profit_nulos,
    COUNTIF(quantity IS NULL) AS quantity_nulos,
    COUNTIF(region IS NULL) AS region_nulos,
    COUNTIF(row_id IS NULL) AS row_id_nulos,
    COUNTIF(sales IS NULL) AS sales_nulos,
    COUNTIF(segment IS NULL) AS segment_nulos,
    COUNTIF(ship_date IS NULL) AS ship_date_nulos,
    COUNTIF(ship_mode IS NULL) AS ship_mode_nulos,
    COUNTIF(shipping_cost IS NULL) AS shipping_cost_nulos,
    COUNTIF(state IS NULL) AS state_nulos,
    COUNTIF(sub_category IS NULL) AS sub_category_nulos,
    COUNTIF(year IS NULL) AS year_nulos,
    COUNTIF(market2 IS NULL) AS market2_nulos,
    COUNTIF(weeknum IS NULL) AS weeknum_nulos
FROM
    `proyecto5-etl.superstore.superstore`;